substitutions:
  name: printer-light

esphome:
  name: ${name}
  name_add_mac_suffix: false # Set to false if you want a predictable name without MAC suffix for MQTT topics

esp32:
  board: m5stack-atom
  framework:
    type: esp-idf
    version: 4.4.8
    platform_version: 5.4.0

logger:

ota:
  - platform: esphome
    id: ota_esphome

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  use_address: 192.168.2.54 # Static IP, ensure it's outside your DHCP range or reserved

light:
  - platform: esp32_rmt_led_strip
    id: led
    pin: GPIO27
    chipset: SK6812
    num_leds: 1
    rgb_order: GRB
    rmt_channel: 0
    default_transition_length: 0.2s
    effects:
      - pulse:
          name: "Slow Pulse"
          transition_length: 1000ms
          update_interval: 1000ms
          min_brightness: 50%
          max_brightness: 100%
      - pulse:
          name: "Fast Pulse"
          transition_length: 300ms
          update_interval: 300ms
          min_brightness: 25%
          max_brightness: 100%

captive_portal:
mqtt:
  id: mqtt_client
  broker: "192.168.1.3"
  port: 1883
  username: !secret mqtt_videobooth_username
  password: !secret mqtt_videobooth_password

  on_connect:
    then:
      - mqtt.publish:
          topic: "${name}/status"
          payload: "online"
          retain: true

  on_message:
    - topic: "${name}/command" # e.g., printer-light/command
      then:
        - lambda: !lambda |-
            ESP_LOGD("rgb_control", "Device '${name}' received command payload: %s", x.c_str());
            std::string payload_str = x;

            if (payload_str == "STANDBY") {
              id(standby).execute();
            } else if (payload_str == "PRINTING") {
              id(printing).execute();
            } else if (payload_str == "FINISHED") {
              id(finished).execute();
            } else if (payload_str == "OFF") {
              id(off).execute();
            } else {
              ESP_LOGW("rgb_control", "Device '${name}' received unknown command: %s", payload_str.c_str());
            }


# Define the scripts
script:
  - id: "standby"
    then:
      - logger.log: "SCRIPT: standby_script executing"
      - light.turn_on:
          id: led
          red: 1.0
          green: 0.647
          blue: 0.31
          brightness: 1.0
          effect: "none" # Important to turn off other effects      

  - id: "printing"
    then:
      - logger.log: "SCRIPT: printing_script executing"
      - light.turn_on:
          id: led
          red: 1.0
          green: 0.0
          blue: 0.0
          brightness: 1.0
          effect: "Fast Pulse" # Matches name in light.effects

  - id: "finished"
    then:
      - logger.log: "SCRIPT: finished_script executing"
      - light.turn_on:
          id: led
          red: 0.0
          green: 1.0
          blue: 0.0
          brightness: 1.0
          effect: "Slow Pulse" # Matches name in light.effects

  - id: "off"
    then:
      - logger.log: "SCRIPT: off_script executing"
      - light.turn_off:
          id: led